const candidatesList = [
    {
        position:"President",
        candidates:[
            {
                firstName:"Dummy1",
                lastName:"Dummy1q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy2",
                lastName:"Dummy2q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy3",
                lastName:"Dummy3q",
                matricNo:"17CZ00075",
            }
        ]
    },
    {
        position:"VicePresident",
        candidates:[
            {
                firstName:"Dummy1",
                lastName:"Dummy1q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy2",
                lastName:"Dummy2q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy3",
                lastName:"Dummy3q",
                matricNo:"17CZ00075",
            }
        ]
    },
    {
        position:"otherPresident",
        candidates:[
            {
                firstName:"Dummy1",
                lastName:"Dummy1q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy2",
                lastName:"Dummy2q",
                matricNo:"17CZ00075",
            },
            {
                firstName:"Dummy3",
                lastName:"Dummy3q",
                matricNo:"17CZ00075",
            }
        ]
    }
]

export default candidatesList;